### ISSUE TITLE
fails if `opts.plugins` is just one plugin (function)

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-postcss#3]
it seems `opts.plugins.length <= 0`, cuz when i do

``` js
var opts = {
  plugins: opal()
}
postcss.render(str, opts)
```

it fails (strange?)

**Comment by RobLoach** [comment]
It fails because there is only one plugin there. `plugins` is expected to take an array.

It is usually bad practice to baby-sit broken code.

**Comment by tunnckoCore** [comment]
Doh yes, lol... Again wrong logic [here](https://github.com/jstransformers/jstransformer-postcss/blob/master/index.js#L11-L13).
